Extended modules v2 stable API for pytest-inmanta (Issue inmanta/pytest-inmanta#235, PR #3398)
# Description

This pull request mainly extends the programmatic API (in most cases only adding existing methods to the stable API) to provide a useful, stable interface for pytest-inmanta to interact with v2 modules (inmanta/pytest-inmanta#240). In addition, it applies some fixes. In detail (ranked from most fundamental to least):
- Made changes to `ModuleLike.from_path` so that it now returns an instance of a subclass of the class it's called on. i.e. `Module.from_path` will now always return a module, never a project. I'm not happy with the typing of this method but I still think it's an improvement in behavior. I think it's more intuitive and it presents more flexibility to the users of the method.
- Replaced `Union[Project, ModuleV1, ModuleV2]` with the less strict `ModuleLike`. This is less type safe but I feel that's an acceptable compromise for the added flexibility if we add this to the stable API. Typing it as `ModuleLike` allows us to someday introduce a `ModuleV3` without breaking the API.
- Added `inmanta.env.mock_process_env` to allow `pytest-inmanta`'s tests to dynamically create new working environments without mucking about too much in core's internals. The implementation accesses an existing object's `__init__` method directly. I believe in this exceptional case we should allow it but let me know if you disagree.
- Applied major version bump early to allow `pytest-inmanta`'s tests to use SemVer to determine modules v2 compatibility.
- Fixed a bug in `from_path` and added tests.
- Removed `options.package_data` section from generated `setup.cfg` file because it's now included in the `MANIFEST.in` file.
- Added newline at the end of generated `MANIFEST.in` file

part of inmanta/pytest-inmanta#235

Mypy diff (caused by less strict typing as discussed above):
```diff
+ src/inmanta/module.py:1155: error: Missing type parameters for generic type "ModuleLike"  [type-arg]
+ src/inmanta/module.py:1159: error: Missing type parameters for generic type "ModuleLike"  [type-arg]
+ src/inmanta/module.py:1161: error: Missing type parameters for generic type "ModuleLike"  [type-arg]
+ src/inmanta/module.py:2086: error: Missing type parameters for generic type Module  [type-arg]
+ src/inmanta/module.py:2087: error: Missing type parameters for generic type Module  [type-arg]
+ src/inmanta/module.py:2089: error: Missing type parameters for generic type Module  [type-arg]
+ src/inmanta/moduletool.py:443: error: Missing type parameters for generic type "ModuleLike"  [type-arg]
```

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [x] End user documentation is included

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design