Ran `mypy --install-types` and added missing types to requirements.dev.txt (PR #3167)
`make mypy-diff` output (red means resolved errors, green means newly exposed errors):
```diff
- src/inmanta/env.py:34: error: Library stubs not installed for "pkg_resources" (or incompatible with Python 3.9)
- src/inmanta/env.py:34: note: Hint: "python3 -m pip install types-setuptools"
+ src/inmanta/env.py:159: error: "Type[WorkingSet]" has no attribute "_build_master"
+ src/inmanta/env.py:250: error: "Requirement" has no attribute "name"
+ src/inmanta/env.py:256: error: "Requirement" has no attribute "url"
+ src/inmanta/env.py:322: error: "Type[WorkingSet]" has no attribute "_build_master"
- src/inmanta/data/__init__.py:50: error: Library stubs not installed for "dateutil" (or incompatible with Python 3.9)
- src/inmanta/data/__init__.py:50: note: Hint: "python3 -m pip install types-python-dateutil"
+ src/inmanta/data/__init__.py:1435: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
+ src/inmanta/data/__init__.py:1436: error: Incompatible types in assignment (expression has type "Field", variable has type "ResourceIdStr")
+ src/inmanta/data/__init__.py:1437: error: Incompatible types in assignment (expression has type "Field", variable has type "datetime")
+ src/inmanta/data/__init__.py:1438: error: Incompatible types in assignment (expression has type "Field", variable has type "Dict[str, Any]")
+ src/inmanta/data/__init__.py:1472: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
+ src/inmanta/data/__init__.py:1473: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
+ src/inmanta/data/__init__.py:1474: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
+ src/inmanta/data/__init__.py:1475: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
+ src/inmanta/data/__init__.py:1476: error: Incompatible types in assignment (expression has type "Field", variable has type "ResourceIdStr")
+ src/inmanta/data/__init__.py:1477: error: Incompatible types in assignment (expression has type "Field", variable has type "int")
+ src/inmanta/data/__init__.py:1478: error: Incompatible types in assignment (expression has type "Field", variable has type "Dict[str, Any]")
+ src/inmanta/data/__init__.py:1479: error: Incompatible types in assignment (expression has type "Field", variable has type "bool")
- src/inmanta/module.py:54: error: Library stubs not installed for "yaml" (or incompatible with Python 3.9)
- src/inmanta/module.py:55: error: Library stubs not installed for "pkg_resources" (or incompatible with Python 3.9)
- src/inmanta/module.py:77: error: Library stubs not installed for "pkg_resources.packaging.version" (or incompatible with Python 3.9)
+ src/inmanta/module.py:77: error: Skipping analyzing "pkg_resources.packaging.version": found module but no type hints or library stubs
- src/inmanta/moduletool.py:35: error: Library stubs not installed for "yaml" (or incompatible with Python 3.9)
- src/inmanta/moduletool.py:37: error: Library stubs not installed for "pkg_resources" (or incompatible with Python 3.9)
- src/inmanta/main.py:30: error: Library stubs not installed for "pkg_resources" (or incompatible with Python 3.9)
- src/inmanta/server/extensions.py:23: error: Library stubs not installed for "pkg_resources" (or incompatible with Python 3.9)
- src/inmanta/server/extensions.py:24: error: Library stubs not installed for "yaml" (or incompatible with Python 3.9)
- src/inmanta/server/services/compilerservice.py:35: error: Library stubs not installed for "dateutil" (or incompatible with Python 3.9)
- src/inmanta/server/services/compilerservice.py:36: error: Library stubs not installed for "dateutil.parser" (or incompatible with Python 3.9)
- src/inmanta/app.py:50: error: Library stubs not installed for "yaml" (or incompatible with Python 3.9)
- src/inmanta/app.py:50: note: Hint: "python3 -m pip install types-PyYAML"
- src/inmanta/app.py:50: note: (or run "mypy --install-types" to install all missing stub packages)
```