Improve line numbering when reporting non-existing attributes on constructors (Issue #5497, PR #5548)
# Description

Fixes #5497

A few remarks:
1. the error is now reported on the key in the assignment (in the testcase that is `d` in `d = "D"`
2. @sanderr I added a field to not have to re-wire the whole class, wdyt?
3. @bartv @sanderr I could also report on the RHS of the assignment, which is easier to implement, but I believe less accurate. What should I report on ?
4. @sanderr do you recall why locatable str is not in fact a child of locatable?

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [ ] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
```
+ src/inmanta/ast/statements/generator.py:565: error: Argument 1 to "TypingException" has incompatible type "LocatableString"; expected "Optional[Locatable]"  [arg-type]
```

- [X] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~