Modules v2: added some warnings and improved exception messages (Issue #3088, PR #3304)
# Description

Added some warnings, improved some exception messages, added tests for both.

closes #3088
closes #3178
closes #3179

## output
Because the exceptions are the focus of this PR are stacked by `__cause__` the actual command output might be hard to follow from the test cases alone. Therefor I'm providing an overview of what the end user would see here.

### 1. load v2 from v1 libs
```
Failed to load module minimalv2module (reported in import minimalv2module (./main.cf:1))
caused by:
  Could not load module minimalv2module
  caused by:
    inmanta.module.ModuleMetadataFileNotFound: Module at /home/sander/documents/projects/inmanta/inmanta-model-test/libs/minimalv2module looks like a v2 module. Please add it as a v2 requirement with `inmanta modules add <module_name>`
```

### 2. incorrectly installed v2 module (`pip install` instead of `inmanta module install`
- case 1: `setup.cfg` missing:
```
Failed to load module minimalv2module (reported in import minimalv2module (./main.cf:1))
caused by:
  Could not load module minimalv2module
  caused by:
    inmanta.module.InvalidModuleException: Invalid module: found module package but it has no setup.cfg. This occurs when you install or build modules from source incorrectly. Always use the `inmanta module` `install` and `build` commands to respectively install and build modules from source.
```
- case 2: no model:
```
Failed to load module minimalv2module (reported in import minimalv2module (./main.cf:1))
caused by:
  Could not load module minimalv2module
  caused by:
    inmanta.module.InvalidModuleException: The module at /home/sander/.virtualenvs/inmanta-core/lib/python3.9/site-packages/inmanta_plugins/minimalv2module contains no model (.cf) files. This occurs when you install or build modules from source incorrectly. Always use the `inmanta module` `install and `build` commands to respectively install and build modules from source.
```

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [x] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design