Make sure that test cases don't change `os.curdir` (PR #3141)
`os.curdir` is a built-in constant and should not be changed by any code. Changing it breaks the standard Python library.

```
>>> import os
>>> d = "/tmp/test/."
>>> os.curdir = "/tmp/"
>>> os.path.exists(d)
False
>>> os.makedirs(d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/tmp/test/.'
```

This PR cleans up the code that changes `os.curdir`. `os.chdir()` should be used to change the current working directory.

- [ ] ~~Attached issue to pull request~~
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~~End user documentation is included or an issue is created for end-user documentation~~

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design