Fix flaky `test_executor_creation_and_venv_usage` test case. (Issue inmanta/inmanta-core#8669, PR #8691)
# Description

Fix flaky `test_executor_creation_and_venv_usage` test case. The test case waited for the executor to shutdown, but not for the executor server to shutdown. The latter was refreshing the `.inmanta_venv_status` file, which caused a conflict with the invocation of the `environment_manager.cleanup_inactive_pool_members()` method resulting in the following exception:

```
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― test_executor_creation_and_venv_usage[23-100] ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

server_config = <module 'inmanta.config' from '/home/arnaud/Documents/projects/inmanta-core/src/inmanta/config.py'>
pip_index = PipIndex(artifact_dir='/tmp/pytest-of-arnaud/pytest-3/pip_index0'), mpmanager_light = <inmanta.agent.forking_executor.MPManager object at 0x7fd8f9a7ab70>

    @with_timeout(30)
    @trace_error_26
    async def test_executor_creation_and_venv_usage(
        server_config, pip_index: PipIndex, mpmanager_light: forking_executor.MPManager
    ) -> None:
        """
        This test verifies the creation and reuse of executors based on their blueprints. It checks whether
        the concurrency aspects and the locking mechanisms work as intended.
        """
        mpmanager_light.process_pool.venv_checkup_interval = 0.1
        requirements1 = ()
        requirements2 = ("pkg1",)
        requirements3 = ("pkg2",)
        pip_config = PipConfig(index_url=pip_index.url)

        # Prepare a source module and its hash
        code = """
    def test():
        return 10
        """.encode()
        sha1sum = hashlib.new("sha1")
        sha1sum.update(code)
        hv: str = sha1sum.hexdigest()
        module_source1 = ModuleSource(
            name="inmanta_plugins.test",
            hash_value=hv,
            is_byte_code=False,
            source=code,
        )
        sources1 = ()
        sources2 = (module_source1,)
        sources3 = (module_source1,)

        initial_version: tuple[int, int] = (3, 11)

        blueprint1 = executor.ExecutorBlueprint(
            pip_config=pip_config, requirements=requirements1, sources=sources1, python_version=initial_version
        )
        blueprint2 = executor.ExecutorBlueprint(
            pip_config=pip_config, requirements=requirements2, sources=sources2, python_version=initial_version
        )
        blueprint3 = executor.ExecutorBlueprint(
            pip_config=pip_config, requirements=requirements3, sources=sources3, python_version=initial_version
        )

        executor_manager = mpmanager_light
        executor_1, executor_2, executor_3 = await asyncio.gather(
            executor_manager.get_executor("agent1", "local:", code_for(blueprint1)),
            executor_manager.get_executor("agent2", "local:", code_for(blueprint2)),
            executor_manager.get_executor("agent3", "local:", code_for(blueprint3)),
        )

        executor_1_venv_status_file = (
            pathlib.Path(executor_1.process.executor_virtual_env.env_path) / const.INMANTA_VENV_STATUS_FILENAME
        )
        executor_2_venv_status_file = (
            pathlib.Path(executor_2.process.executor_virtual_env.env_path) / const.INMANTA_VENV_STATUS_FILENAME
        )
        executor_3_venv_status_file = (
            pathlib.Path(executor_3.process.executor_virtual_env.env_path) / const.INMANTA_VENV_STATUS_FILENAME
        )

        logger.warning("Touching %s now", executor_2_venv_status_file)
        old_datetime = datetime.datetime(year=2022, month=9, day=22, hour=12, minute=51, second=42)
        # This part of the test is a bit subtle because we rely on the fact that there is no context switching between the
        # modification override of the inmanta file and the retrieval of the last modification of the file
        os.utime(
            executor_2_venv_status_file,
            (datetime.datetime.now().timestamp(), old_datetime.timestamp()),
        )

        old_check_executor1 = executor_1.process.executor_virtual_env.last_used
        old_check_executor2 = executor_2.process.executor_virtual_env.last_used

        # We wait for the refresh of the venv status files
        await asyncio.sleep(0.2)
        logger.warning("Sleeping done")

        new_check_executor1 = executor_1.process.executor_virtual_env.last_used
        new_check_executor2 = executor_2.process.executor_virtual_env.last_used

        assert new_check_executor1 > old_check_executor1
        assert new_check_executor2 > old_check_executor2
        assert (datetime.datetime.now().astimezone() - new_check_executor2).seconds <= 2

        async def wait_for_agent_stop_running(executor: MPExecutor) -> bool:
            """
            Wait for the agent to stop running
            """
            return not executor.running

        # Now we want to check if the cleanup is working correctly
        await executor_manager.stop_for_agent("agent1")
        await retry_limited(wait_for_agent_stop_running, executor=executor_1, timeout=10)
        # First we want to override the modification date of the `inmanta_venv_status` file
        os.utime(
            executor_1_venv_status_file, (datetime.datetime.now().astimezone().timestamp(), old_datetime.astimezone().timestamp())
        )
        environment_manager = mpmanager_light.process_pool.environment_manager
        venv_dir = pathlib.Path(environment_manager.envs_dir)
        assert len([e for e in venv_dir.iterdir()]) == 3, "We should have two Virtual Environments for our 2 executors!"
        # We remove the old VirtualEnvironment
        logger.debug("Calling cleanup_virtual_environments")
        await environment_manager.cleanup_inactive_pool_members()
        logger.debug("cleanup_virtual_environments ended")

        venvs = {str(e) for e in venv_dir.iterdir()}
>       assert len(venvs) == 2, "Only two Virtual Environment should exist!"  # Venv one is gone
E       AssertionError: Only two Virtual Environment should exist!
E       assert 3 == 2
E        +  where 3 = len({'/tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/354a1fba8a1d5af0b7d5906aa373ad9a', '...d', '/tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/cb4d292fac637de63b9c2d321052801d'})

tests/forking_agent/test_agent_executor.py:414: AssertionError
------------------------------------------------------------------------ Captured stdout call -------------------------------------------------------------------------
inmanta                  INFO    Not setting up telemetry
asyncio                  DEBUG   Using selector: EpollSelector
inmanta.executor.2f8c04be6fbd303eb3d3e868d10b943eINFO    Started executor with PID: 27321
inmanta.protocol.endpointsDEBUG   Start transport for client agent
inmanta.env              INFO    Initializing virtual environment at /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/cb4d292fac637de63b9c2d321052801d
inmanta.executor.2f8c04be6fbd303eb3d3e868d10b943eTRACE   Touching venv status /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/cb4d292fac637de63b9c2d321052801d/.inmanta_venv_status, then sleeping 0.100000
inmanta.executor.2f8c04be6fbd303eb3d3e868d10b943eINFO    Starting for agent1
inmanta.executor.2f8c04be6fbd303eb3d3e868d10b943eTRACE   Touching venv status /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/cb4d292fac637de63b9c2d321052801d/.inmanta_venv_status, then sleeping 0.100000
inmanta.executor.2f8c04be6fbd303eb3d3e868d10b943eTRACE   Touching venv status /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/cb4d292fac637de63b9c2d321052801d/.inmanta_venv_status, then sleeping 0.100000
inmanta.executor.2f8c04be6fbd303eb3d3e868d10b943eTRACE   Touching venv status /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/cb4d292fac637de63b9c2d321052801d/.inmanta_venv_status, then sleeping 0.100000
inmanta.executor.2f8c04be6fbd303eb3d3e868d10b943eTRACE   Touching venv status /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/cb4d292fac637de63b9c2d321052801d/.inmanta_venv_status, then sleeping 0.100000
inmanta                  INFO    Not setting up telemetry
asyncio                  DEBUG   Using selector: EpollSelector
inmanta.executor.c3a799eea52e04afbf9733a162cd0a67INFO    Started executor with PID: 27328
inmanta.protocol.endpointsDEBUG   Start transport for client agent
inmanta.env              INFO    Initializing virtual environment at /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/8c9b7631bdea98e66ff84ab146c03f8d
inmanta.loader           INFO    Deploying code (hv=bd1f57d3ddc79d7afa9ff5038980309f458a7d08, module=inmanta_plugins.test)
inmanta.executor.c3a799eea52e04afbf9733a162cd0a67TRACE   Touching venv status /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/8c9b7631bdea98e66ff84ab146c03f8d/.inmanta_venv_status, then sleeping 0.100000
inmanta.loader           DEBUG   Loading module: inmanta_plugins.test
inmanta.loader           INFO    Loaded module inmanta_plugins.test
inmanta.executor.c3a799eea52e04afbf9733a162cd0a67INFO    Starting for agent2
inmanta                  INFO    Not setting up telemetry
asyncio                  DEBUG   Using selector: EpollSelector
inmanta.executor.9eb53315fcbcbc650869c6001774a06dINFO    Started executor with PID: 27331
inmanta.protocol.endpointsDEBUG   Start transport for client agent
inmanta.env              INFO    Initializing virtual environment at /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/354a1fba8a1d5af0b7d5906aa373ad9a
inmanta.loader           INFO    Deploying code (hv=bd1f57d3ddc79d7afa9ff5038980309f458a7d08, module=inmanta_plugins.test)
inmanta.executor.9eb53315fcbcbc650869c6001774a06dTRACE   Touching venv status /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/354a1fba8a1d5af0b7d5906aa373ad9a/.inmanta_venv_status, then sleeping 0.100000
inmanta.loader           DEBUG   Loading module: inmanta_plugins.test
inmanta.loader           INFO    Loaded module inmanta_plugins.test
inmanta.executor.9eb53315fcbcbc650869c6001774a06dINFO    Starting for agent3
inmanta.executor.2f8c04be6fbd303eb3d3e868d10b943eTRACE   Touching venv status /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/cb4d292fac637de63b9c2d321052801d/.inmanta_venv_status, then sleeping 0.100000
inmanta.executor.c3a799eea52e04afbf9733a162cd0a67TRACE   Touching venv status /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/8c9b7631bdea98e66ff84ab146c03f8d/.inmanta_venv_status, then sleeping 0.100000
inmanta.executor.9eb53315fcbcbc650869c6001774a06dTRACE   Touching venv status /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/354a1fba8a1d5af0b7d5906aa373ad9a/.inmanta_venv_status, then sleeping 0.100000
inmanta.executor.2f8c04be6fbd303eb3d3e868d10b943eTRACE   Touching venv status /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/cb4d292fac637de63b9c2d321052801d/.inmanta_venv_status, then sleeping 0.100000
inmanta.executor.c3a799eea52e04afbf9733a162cd0a67TRACE   Touching venv status /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/8c9b7631bdea98e66ff84ab146c03f8d/.inmanta_venv_status, then sleeping 0.100000
inmanta.executor.9eb53315fcbcbc650869c6001774a06dTRACE   Touching venv status /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/354a1fba8a1d5af0b7d5906aa373ad9a/.inmanta_venv_status, then sleeping 0.100000
inmanta.executor         INFO    Stopping for agent1
inmanta.executor.2f8c04be6fbd303eb3d3e868d10b943eTRACE   Touching venv status /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/cb4d292fac637de63b9c2d321052801d/.inmanta_venv_status, then sleeping 0.100000
inmanta.executor.2f8c04be6fbd303eb3d3e868d10b943eINFO    Stopping
inmanta.executor.2f8c04be6fbd303eb3d3e868d10b943eINFO    Connection lost
inmanta.executor.2f8c04be6fbd303eb3d3e868d10b943eINFO    Stopped with PID: 27321
-------------------------------------------------------------------------- Captured log call --------------------------------------------------------------------------
11:53:08.453 WARNING Touching /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/8c9b7631bdea98e66ff84ab146c03f8d/.inmanta_venv_status now
11:53:08.654 WARNING Sleeping done
11:53:08.656 ERROR An error occurred while removing the venv located /tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/cb4d292fac637de63b9c2d321052801d
Traceback (most recent call last):
  File "/home/arnaud/Documents/projects/inmanta-core/src/inmanta/agent/executor.py", line 356, in remove_venv
    shutil.rmtree(self.env_path)
  File "/usr/lib64/python3.12/shutil.py", line 759, in rmtree
    _rmtree_safe_fd(stack, onexc)
  File "/usr/lib64/python3.12/shutil.py", line 703, in _rmtree_safe_fd
    onexc(func, path, err)
  File "/usr/lib64/python3.12/shutil.py", line 662, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=dirfd)
OSError: [Errno 39] Directory not empty: '/tmp/pytest-of-arnaud/pytest-3/test_executor_creation_and_ven68/executors/venvs/cb4d292fac637de63b9c2d321052801d'
```

closes #8669

# Self Check:

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~~End user documentation is included or an issue is created for end-user documentation~~
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)