Use asyncpg instead of SQLAlchemy for database connection pooling. (Issue #8865, PR #8922)
# Description

Use asyncpg pool instead of relying on sqlalchemy's pool (draft design on [slack](https://inmanta.slack.com/archives/CKRF0C8R3/p1742812272466829)).
Reverts parts of https://github.com/inmanta/inmanta-core/commit/3c4bb011ae514449b78696766a1a4a4e0f34bc69#diff-bb1dfcdff553f454a9e9c4dd88e8b19088f5dcdc2d2c32da810b127dc344d705

closes https://github.com/inmanta/inmanta-core/issues/8865

"minimal" mypy diff: (the rest is re-ordereing or re-introducing previous errors because of the revert)

```
src/inmanta/data/__init__.py:6751: error: Incompatible types in "await" (actual type "AsyncContextManager[Connection]", expected type "Awaitable[Any]")  [misc]
src/inmanta/data/__init__.py:6751: error: Returning Any from function declared to return "PoolAcquireContext"  [no-any-return]
```

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)