Fix mypy errors (PR #8739)
# Description

bumping mypy to v1.15 raised the following new errors:

```
src/inmanta/ast/__init__.py:34: error: Cannot assign to final name "TYPE_CHECKING"  [misc]
src/inmanta/ast/type.py:41: error: Cannot assign to final name "TYPE_CHECKING"  [misc]
src/inmanta/ast/attribute.py:30: error: Cannot assign to final name "TYPE_CHECKING"  [misc]
src/inmanta/ast/statements/assign.py:68: error: Cannot assign to final name "TYPE_CHECKING"  [misc]
src/inmanta/ast/statements/generator.py:81: error: Cannot assign to final name "TYPE_CHECKING"  [misc]
src/inmanta/execute/proxy.py:38: error: Cannot assign to final name "TYPE_CHECKING"  [misc]
src/inmanta/ast/entity.py:55: error: Cannot assign to final name "TYPE_CHECKING"  [misc]
src/inmanta/module.py:78: error: Cannot assign to final name "TYPE_CHECKING"  [misc]
src/inmanta/module.py:1127: error: Item "<subclass of "TextIOBase" and "str">" of "<subclass of "TextIOBase" and "str"> | <subclass of "TextIOBase" and "TextIO">" has no attribute "name"  [union-attr]
src/inmanta/module.py:1146: error: Item "<subclass of "TextIOBase" and "str">" of "<subclass of "TextIOBase" and "str"> | <subclass of "TextIOBase" and "TextIO">" has no attribute "name"  [union-attr]
src/inmanta/module.py:1151: error: Item "<subclass of "TextIOBase" and "str">" of "<subclass of "TextIOBase" and "str"> | <subclass of "TextIOBase" and "TextIO">" has no attribute "name"  [union-attr]
src/inmanta/module.py:1240: error: Item "<subclass of "TextIOBase" and "str">" of "<subclass of "TextIOBase" and "str"> | <subclass of "TextIOBase" and "TextIO">" has no attribute "name"  [union-attr]
```
------

Error of type 1 e.g.  ` error: Cannot assign to final name "TYPE_CHECKING"  [misc]`

was caused by the fact that `TYPE_CHECKING` is now of type [final](https://mypy.readthedocs.io/en/stable/final_attrs.html#final-names) -> new mypy type that disallows assigning a value to a variable after it was initialized

Solution:  remove the try/catch block around the import (I think this was kept for compatibility with python <= 3.9 ?) + the assignation.

-----

Error of type 2 e.g. `error: Item "<subclass of "TextIOBase" and "str">" of "<subclass of "TextIOBase" and "str"> | <subclass of "TextIOBase" and "TextIO">" has no attribute "name"  [union-attr]`

I think these are an actual bug

Solution change the instance type check from `TextIOBase` to `TextIOWrapper`, which is the type of the objects returned by `open()` and has a `name` attribute

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)