Added logging and config to agent fork infrastructure (PR #7236)
1. make sure we load config
2. make sure we configure logging
3. move to typed IPC (still a bit weird)

@bartv the IPC feels a bit weird to me like this. WDYT

# Description

* Short description here *

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
Mypy can't figure these out
```
src/inmanta/protocol/ipc_light.py:212: error: Invalid index type "UUID | None" for "dict[UUID, Future[object]]"; expected type "UUID"  [index]
src/inmanta/server/services/resourceservice.py:986: error: Argument 6 to "propagate_resource_state_if_stale" of "ResourceService" has incompatible type "ResourceState | None"; expected "ResourceState"  [arg-type]
```
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)