removed redundant import of setuptools.find_namespace_packages (PR #3341)
# Description

Removed what seems to be a redundant import of setuptools.find_namespace_packages introduced in #3164. @arnaudsjs could you confirm this is indeed no longer required?
In addition to being redundant this somehow caused the docs build to fail with "ImportError: cannot import name 'find_namespace_packages'".

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] ~~Attached issue to pull request~~
- [x] Changelog entry
- [x] ~~Type annotations are present~~
- [x] ~~Code is clear and sufficiently documented~~
- [x] ~~No (preventable) type errors (check using make mypy or make mypy-diff)~~
- [x] ~~Sufficient test cases (reproduces the bug/tests the requested feature)~~
- [x] ~~Correct, in line with design~~
- [x] ~~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design