Start event loop for `inmanta --version` (PR #6183)
`inmanta --version` with an expired license currently leads to the following output because `inmanta-license` tries to use the scheduler to log a warning.

```
Traceback (most recent call last):
  File "/home/sander/documents/projects/inmanta/inmanta-license/src/inmanta_license/license.py", line 671, in _load_entitlements_file
    jwt_data = jwt.decode(token_data, key=pk_pem, audience=self.licensee, algorithms=["RS512"])
  File "/home/sander/.virtualenvs/tmp-2dc293d8facc2d4/lib/python3.9/site-packages/jwt/api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "/home/sander/.virtualenvs/tmp-2dc293d8facc2d4/lib/python3.9/site-packages/jwt/api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "/home/sander/.virtualenvs/tmp-2dc293d8facc2d4/lib/python3.9/site-packages/jwt/api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/home/sander/.virtualenvs/tmp-2dc293d8facc2d4/lib/python3.9/site-packages/jwt/api_jwt.py", line 304, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sander/.virtualenvs/tmp-2dc293d8facc2d4/bin/inmanta", line 8, in <module>
    sys.exit(app())
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/app.py", line 737, in app
    print_versions_installed_components_and_exit()
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/app.py", line 697, in print_versions_installed_components_and_exit
    app_context = bootloader.load_slices()
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/server/bootloader.py", line 233, in load_slices
    return self._collect_slices(exts, only_register_environment_settings)
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/server/bootloader.py", line 223, in _collect_slices
    ext_module.setup(myctx)
  File "/home/sander/documents/projects/inmanta/inmanta-license/src/inmanta_ext/license/extension.py", line 13, in setup
    application.set_feature_manager(LicensedFeatureManager())
  File "/home/sander/documents/projects/inmanta/inmanta-license/src/inmanta_license/license.py", line 625, in __init__
    self._load_entitlements_file()
  File "/home/sander/documents/projects/inmanta/inmanta-license/src/inmanta_license/license.py", line 673, in _load_entitlements_file
    self._repeat_warning("The entitlements file expired, running unlicensed version! Contact support@inmanta.com")
  File "/home/sander/documents/projects/inmanta/inmanta-license/src/inmanta_license/license.py", line 629, in _repeat_warning
    self._scheduler.add_action(get_warning_func(message), IntervalSchedule(60, 0))
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/util.py", line 332, in add_action
    handle: asyncio.TimerHandle = asyncio.get_running_loop().call_later(schedule_typed.get_initial_delay(), action_function)
RuntimeError: no running event loop
```

This PR makes sure we start an event loop before loading the slices. Remaining, less urgent, issue: inmanta/inmanta-license#520.