No longer depend on implicit event loop creation on any thread. (PR #5883)
# Description

- Refactored bulk of the codebase to no longer depend on implicit event loop creation on the main thread because it has been deprecated. Migrated from `tornado` to `asyncio` event loops in those places
- Dropped `AnyThreadLoopEventPolicy` because with the change mentioned above all threads are treated equally, therefore it is no longer required.
- Fixed some race conditions in test cases that triggered consistenly with my changes.
- `inmanta.app` still uses `tornado` event loops because it wasn't as straightforward to factor it out there. I did make sure the implementation doesn't depend on implicit event loop creation on the main thread anymore.

Mypy diff (red is good)
```diff
- src/inmanta/protocol/endpoints.py:438: error: Returning Any from function declared to return "Result"  [no-any-return]
- src/inmanta/plugins.py:138: error: Module "tornado.ioloop" does not explicitly export attribute "TimeoutError"  [attr-defined]
- src/inmanta/plugins.py:141: error: Returning Any from function declared to return "T"  [no-any-return]
- src/inmanta/server/protocol.py:445: error: Incompatible types in assignment (expression has type "object", variable has type "None")  [assignment]
```

closes #5389
closes #5392
Related to inmanta/lsm#539, assumed to allow major simplification of [inmanta/lsm#564@cd9c3e97](https://github.com/inmanta/lsm/pull/564/files/cd9c3e972c8395c186e0362a695512f251be03b4): `AnyThreadLoopEventPolicy` can just be dropped without the need for the `asyncio_thread_wrapper`

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)