Added clear error message when attempting to install v2 module without v2 module source (Issue #3619, PR #3622)
# Description

The error message when attempting to install a v2 module (for example via `inmanta module add --v2`) when no v2 module source has been configured was very unhelpful, as @FloLey encountered this week. I've created this ticket as a response. Since it has never been vetted during planning I'm requesting both your reviews @arnaudsjs @wouterdb.

closes #3619

# Output

```
(inmanta-core) sander@arthur:~/documents/projects/inmanta/inmanta-model-test$ inmanta project install
Could not load module std
caused by:
  Exception: Attempting to install a v2 module but no v2 module source is configured. Add at least one repo of type "package" to the project config file.

(inmanta-core) sander@arthur:~/documents/projects/inmanta/inmanta-model-test$ inmanta module add --v2 std --override
Attempting to install a v2 module but no v2 module source is configured. Add at least one repo of type "package" to the project config file.

```

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [x] ~~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design