Add cache to validate_type and improve performance of dict and list construction (Issue #7041, PR #7179)
# Description

closes #7041

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
```
src/inmanta/validation_type.py:106: error: Incompatible types in assignment (expression has type "object", variable has type "Mapping[str, object] | None")  [assignment]
```

overloaded typedefs causes issues

```python
    @overload
    @classmethod
    def unwrap(cls, item: "DictProxy") -> Mapping[str, object]: ...

    @overload
    @classmethod
    def unwrap(cls, item: "SequenceProxy") -> Sequence[object]: ...

    @overload
    @classmethod
    def unwrap(cls, item: "None") -> NoneValue: ...

    # This one is not correct
    # @overload
    # @classmethod
    # def unwrap(cls, item: "DynamicProxy") -> "Instance": ...

    @overload
    @classmethod
    def unwrap(cls, item: object) -> object: ...

```
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)