Add support to cancel background tasks when the scheduler is stopped (PR #4045)
The scheduler, which schedules background tasks, didn't have support to cancel tasks that are executing. It only has support to stop tasks that were scheduled to run, but are not yet executing. This caused tests to fail in the following scenario:

* The scheduler starts executing a background task that requires interaction with the database
* The stop method of the server is called
* The stop method of the scheduler is called, but that doesn't cancel the task that is already executing
* The stop method of the database slice is called, which stops the connection pool to the database
* The executing background tasks fails, because it cannot connect to the database.

This PR adds support to the scheduler to cancel all background tasks that are executing when the stop method of the server is called.

Relevant section from the teardown log of the failing test case:

```
DEBUG    inmanta.data:__init__.py:5590 Disconnecting data classes
ERROR    inmanta.util:util.py:114 Uncaught exception while executing scheduled action
Traceback (most recent call last):
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib/python3.9/site-packages/inmanta/data/__init__.py", line 1663, in perform_query
    async for record in con.cursor(query, *values):
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib64/python3.9/site-packages/asyncpg/cursor.py", line 214, in __anext__
    self._state = await self._connection._get_statement(
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib64/python3.9/site-packages/asyncpg/connection.py", line 398, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
  File "asyncpg/protocol/protocol.pyx", line 865, in asyncpg.protocol.protocol.BaseProtocol._dispatch_result
asyncpg.exceptions._base.InternalClientError: got result for unknown protocol state 3

**During handling of the above exception, another exception occurred:**

Traceback (most recent call last):
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib/python3.9/site-packages/inmanta/server/services/notificationservice.py", line 64, in _cleanup
    await data.Notification.clean_up_notifications()
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib/python3.9/site-packages/inmanta/data/__init__.py", line 5540, in clean_up_notifications
    environments = await Environment.get_list()
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib/python3.9/site-packages/inmanta/data/__init__.py", line 2166, in get_list
    return await super().get_list(
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib/python3.9/site-packages/inmanta/data/__init__.py", line 1193, in get_list
    return await cls.get_list_with_columns(
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib/python3.9/site-packages/inmanta/data/__init__.py", line 1238, in get_list_with_columns
    result = await cls.select_query(sql_query, values, no_obj=no_obj, connection=connection)
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib/python3.9/site-packages/inmanta/data/__init__.py", line 1672, in select_query
    return await perform_query(con)
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib/python3.9/site-packages/inmanta/data/__init__.py", line 1668, in perform_query
    return result
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib64/python3.9/site-packages/asyncpg/transaction.py", line 66, in __aexit__
    self._check_conn_validity('__aexit__')
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib64/python3.9/site-packages/asyncpg/connresource.py", line 41, in _check_conn_validity
    raise exceptions.InterfaceError(
asyncpg.exceptions._base.InterfaceError: cannot call Transaction.__aexit__(): the underlying connection is closed
ERROR    inmanta.server.services.compilerservice:compilerservice.py:513 The following exception occurred while cleaning up old compiler reports
Traceback (most recent call last):
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib/python3.9/site-packages/inmanta/server/services/compilerservice.py", line 508, in _cleanup
    await data.Compile.delete_older_than(oldest_retained_date)
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib/python3.9/site-packages/inmanta/data/__init__.py", line 3179, in delete_older_than
    await cls._execute_query(query, oldest_retained_date, connection=connection)
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib/python3.9/site-packages/inmanta/data/__init__.py", line 1049, in _execute_query
    return await con.execute(query, *values)
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib64/python3.9/site-packages/asyncpg/pool.py", line 993, in __aexit__
    await self.pool.release(con)
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib64/python3.9/site-packages/asyncpg/pool.py", line 855, in release
    self._check_init()
  File "/home/jenkins/workspace/core/inmanta-core-test-coverage/.tox/py39/lib64/python3.9/site-packages/asyncpg/pool.py", line 948, in _check_init
    raise exceptions.InterfaceError('pool is closed')
asyncpg.exceptions._base.InterfaceError: pool is closed
DEBUG    asyncio:selector_events.py:59 Using selector: EpollSelector
```

- [ ] ~~Attached issue to pull request~~
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~~End user documentation is included or an issue is created for end-user documentation~~

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design