Enabled mypy's `strict_equality` option (Issue #5380, PR #5380)
# Description

- Moved mypy config to pyproject.toml
- Added `strict_equality = true`
- Fixed fallout
  - small bug in cycle detection for relation precedence policy
  - `inmanta.config.is_bool` used a private library method, I changed it to use equivalent behavior through the public API instead.
  - v1 module finder used deprecated `find_module`. I implemented `find_spec` instead.
  - some incorrect type annotations

Resulting diff below (red is good). There is one new error but I decided not to fix it because it is due to incorrect typing in typeshed, which has already been fixed in the latest mypy nightlies, so it should disappear soon.
```diff
- src/inmanta/config.py:214: error: Returning Any from function declared to return "bool"  [no-any-return]
- src/inmanta/config.py:214: error: "ConfigParser" has no attribute "_convert_to_boolean"  [attr-defined]
- src/inmanta/loader.py:483: error: Argument 1 to "remove" of "list" has incompatible type "PluginModuleFinder"; expected "_MetaPathFinder"  [arg-type]
+ src/inmanta/loader.py:510: error: Argument 2 of "find_spec" is incompatible with supertype "MetaPathFinder"; supertype defines the argument type as "Optional[Sequence[Union[bytes, str]]]"  [override]
+ src/inmanta/loader.py:510: note: This violates the Liskov substitution principle
+ src/inmanta/loader.py:510: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
- src/inmanta/data/__init__.py:5172: error: Argument 1 to "list" has incompatible type "Set[str]"; expected "Iterable[Dict[str, Any]]"  [arg-type]
- src/inmanta/data/__init__.py:5184: error: Invalid index type "Dict[str, Any]" for "Dict[str, List[str]]"; expected type "str"  [index]
- src/inmanta/data/__init__.py:5185: error: Argument 1 to "extend" of "list" has incompatible type "List[str]"; expected "Iterable[Dict[str, Any]]"  [arg-type]
- src/inmanta/data/__init__.py:5189: error: Incompatible return value type (got "Tuple[Set[str], Set[Any]]", expected "Tuple[Set[ResourceIdStr], Set[ResourceIdStr]]")  [return-value]
- src/inmanta/server/services/resourceservice.py:316: error: Incompatible types in assignment (expression has type "Tuple[Set[ResourceIdStr], Set[ResourceIdStr]]", variable has type "Optional[Tuple[Set[ResourceVersionIdStr], List[ResourceVersionIdStr]]]")  [assignment]
- src/inmanta/server/services/resourceservice.py:319: error: "None" object is not iterable  [misc]
```

Closes #5048

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] ~~Sufficient test cases (reproduces the bug/tests the requested feature)~~
- [x] Correct, in line with design
- [x] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )