Fix new mypy errors discovered after bumping to v1.12.1. (PR #8250)
# Description

dependabot pr updating mypy was failing because of the following mypy errors:
```
[2024-10-22T09:02:08.882Z] mypy: commands[1] /home/jenkins/workspace/dencies-asynccorepytest--2.139.0/project/inmanta-core> sh -c 'python -m mypy --soft-error-limit=-1 --junit-xml mypy.xml --cobertura-xml-report coverage -p inmanta | mypy-baseline filter --no-colors'
[2024-10-22T09:02:19.177Z] src/inmanta/data/__init__.py:3894: error: Argument "environment_variables" to "CompileDetails" has incompatible type "Any | None"; expected "dict[str, str]"  [arg-type]
[2024-10-22T09:02:19.177Z] src/inmanta/data/dataview.py:733: error: Argument "environment_variables" to "CompileReport" has incompatible type "Any | None"; expected "dict[str, str]"  [arg-type]
[2024-10-22T09:02:19.177Z] src/inmanta/server/services/paramservice.py:290: error: Incompatible types in assignment (expression has type "Any | None", variable has type "ResourceIdStr")  [assignment]
[2024-10-22T09:02:19.177Z] src/inmanta/server/services/paramservice.py:299: error: Argument 3 to "_update_param" of "ParameterService" has incompatible type "Any | None"; expected "str"  [arg-type]
[2024-10-22T09:02:19.177Z] src/inmanta/server/services/paramservice.py:299: error: Argument 6 to "_update_param" of "ParameterService" has incompatible type "Any | None"; expected "dict[str, Any]"  [arg-type]
```

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)