Fix race condition in the `test_compile_details()` test case. The background task that removes old compile reports was removing the compile reports created by the `env_with_compiles` fixture. (PR #4033)
# Description

This PR fixes a race condition in the `test_compile_details()` test case. The background task that removes old compile reports was removing the compile reports created by the `env_with_compiles` fixture, causing the test case to fail with the following exception:

```
_____________________________ test_compile_details _____________________________

server = <inmanta.server.protocol.Server object at 0x7f8b8c0eed60>
client = <inmanta.protocol.endpoints.Client object at 0x7f8b726bda00>
env_with_compiles = ('5565bfc6-df9d-4517-914c-5b352d6b4565', [UUID('f36a91ab-3df5-42a7-942b-2f1b78a1e716'), UUID('73a916f6-8d60-4f88-ba52-... 0), datetime.datetime(2021, 9, 9, 11, 1), datetime.datetime(2021, 9, 9, 11, 2), datetime.datetime(2021, 9, 9, 11, 3)])

    async def test_compile_details(server, client, env_with_compiles):
        environment, ids, compile_requested_timestamps = env_with_compiles

        # A compile that has no substitute_compile_id, and has reports
        result = await client.compile_details(environment, ids[0])
>       assert result.code == 200
E       assert 404 == 200
E         +404
E         -200
```

# Self Check:

- [ ] ~~Attached issue to pull request~~
- [x] Changelog entry
- [ ] ~~Type annotations are present~~
- [ ] ~~Code is clear and sufficiently documented~~
- [ ] ~~No (preventable) type errors (check using make mypy or make mypy-diff)~~
- [ ] ~~Sufficient test cases (reproduces the bug/tests the requested feature)~~
- [ ] ~~Correct, in line with design~~
- [ ] ~~End user documentation is included or an issue is created for end-user documentation~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design