Added explainer for modules v2 found in v1 module path (Issue #3325, PR #3345)
# Description

- Restructured `inmanta.compiler.help.explainer` to be more generic and more strictly (and correctly) typed.
- Introduced explainer for when a v2 module is found in the v1 module path

@wouterdb since we've talked about this before I'm requesting your review first, with an initial focus on the quality and completeness of the explanation. I'm not sure I've covered all potential scenario's. Once we've converged on this part I'll add @arnaudsjs for the full review. If you feel like an in-person discussion about the explanation would be useful, I'm available for that.

If you feel like the explainer improvements should go into iso4 to more easily add explainers to both master and iso4 (without conflicts) in the future, let me know.

closes #3325

# mypy-diff

(red is good, the green one on the last line was previously present but hidden)
```diff
+ stubs/asyncpg/types.pyi:5: error: Skipping analyzing 'asyncpg.pgproto.types': found module but no type hints or library stubs  [import]
- stubs/asyncpg/types.pyi:5: error: Skipping analyzing 'asyncpg.pgproto.types': found module but no type hints or library stubs  [import]
- src/inmanta/compiler/help/explainer.py:99: error: Argument 2 to "__init__" of "JinjaExplainer" has incompatible type "Type[ModifiedAfterFreezeException]"; expected "Type"  [arg-type]
- src/inmanta/compiler/help/explainer.py:102: error: "CompilerException" has no attribute "stmt"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:104: error: "CompilerException" has no attribute "stmt"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:105: error: "CompilerException" has no attribute "attribute"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:106: error: "CompilerException" has no attribute "stmt"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:109: error: "CompilerException" has no attribute "stmt"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:111: error: "CompilerException" has no attribute "attribute"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:112: error: "CompilerException" has no attribute "stmt"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:115: error: "CompilerException" has no attribute "stmt"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:116: error: "CompilerException" has no attribute "attribute"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:116: error: "CompilerException" has no attribute "stmt"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:120: error: "CompilerException" has no attribute "attribute"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:121: error: "CompilerException" has no attribute "instance"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:122: error: "CompilerException" has no attribute "resultvariable"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:123: error: "CompilerException" has no attribute "value"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:125: error: "CompilerException" has no attribute "reverse"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:126: error: "CompilerException" has no attribute "reverse"  [attr-defined]
- src/inmanta/compiler/help/explainer.py:127: error: "CompilerException" has no attribute "resultvariable"  [attr-defined]
+ src/inmanta/compiler/help/explainer.py:150: error: Item "None" of "Optional[RelationAttribute]" has no attribute "get_name"  [union-attr]
```

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] ~~Sufficient test cases (reproduces the bug/tests the requested feature)~~
- [x] Correct, in line with design
- [x] ~~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design