Make sure openapi UI works when ssl is enabled (Issue #5680, PR #6618)
# Description

Make sure proper url is produced

closes #5680

# Mypy

I introduced a type error, but I think this is the pydantic mypy extension being imprecise, because it works just fine and the way I use it now is the way it is documented....

(e.g. the example [here](https://docs.pydantic.dev/1.10/usage/types/#url-properties) )

```diff
+ src/inmanta/protocol/openapi/converter.py:75: error: Argument "url" to "Server" has incompatible type "str"; expected "AnyUrl"  [arg-type]
```

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)